[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "0c0bc9607a4dd0db6fc9571dd2c34d66801218d0"
os = "macos"

    [[SSGraphBLAS.download]]
    sha256 = "12f130ac145cdf112501d4eb30caeb2dbcec26d3c08846284530553fef9556ac"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.aarch64-apple-darwin.tar.gz"
[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "813bd0e2f24697356fc2a65c85d09a4262a22c00"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "c373decda9a2c29b6a91632bd7d2c4f1dda217decbde50725fcec31d8c6cdd2f"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.aarch64-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "737ed1033c5012dc9732b2cf9f1be5b64b443eab"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "4f5105cf07d69326d8a683c1361cc68eda176e64922f7c419a935e162fcf9768"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.aarch64-linux-musl.tar.gz"
[[SSGraphBLAS]]
arch = "aarch64"
git-tree-sha1 = "58a2d4468545d6e4c4f40c9eacc71595bc876291"
os = "freebsd"

    [[SSGraphBLAS.download]]
    sha256 = "391d735bb457216ada398c0f6d2a59ce87f07843a645524c41d2d44606f3c228"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.aarch64-unknown-freebsd.tar.gz"
[[SSGraphBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3734cd5df7e0bad0bcadbe8f92bc72276d4caba3"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "4508306c83ef6ce4dc231b2a91f16497e495b427bb026f870748d4385487a998"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.armv6l-linux-gnueabihf.tar.gz"
[[SSGraphBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0172e5f48a82d90f03d0ca7e6e9241ccf7b7bc45"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "73bef6f0c3f3457df7abcace88e294b0ef1b4cb43c8d708d10d6a73dc1f4505a"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.armv6l-linux-musleabihf.tar.gz"
[[SSGraphBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "975491d02f55bdb65be7afa723b98a381117a0a5"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "b9a8a7187d41017f7ea53a58f41ed9dcc41d6c0c313b849351041ca2ef1e4c1a"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.armv7l-linux-gnueabihf.tar.gz"
[[SSGraphBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "641a61e0ce4732d021c8e1c9cccb2ec3bea55064"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "dcdbc0ca8b84b3b94b0206625e81b87f6359bee11d517ea74fe4d4ba28eb16ac"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.armv7l-linux-musleabihf.tar.gz"
[[SSGraphBLAS]]
arch = "i686"
git-tree-sha1 = "7a43e6f7080741e7889867cad06a801b96ffe750"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "38867f2633472cb5bf73278026db029ce661207fcea2a4e28872fb7755a83c6a"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.i686-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "i686"
git-tree-sha1 = "971171d29e8331e94abc128ee60f6ceadfffc3e5"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "527dd458b69cf578f2259dfeef3ceaa5d90537fefd0f28c757c0e314fd3d9b3d"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.i686-linux-musl.tar.gz"
[[SSGraphBLAS]]
arch = "i686"
git-tree-sha1 = "ca2252ed5f0bf1cd5e2d29855906d8d7356fa506"
os = "windows"

    [[SSGraphBLAS.download]]
    sha256 = "58d1d3b88ccb881a5a8b40a167bcdc11147d383b75cffef4f101de488136ef13"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.i686-w64-mingw32.tar.gz"
[[SSGraphBLAS]]
arch = "powerpc64le"
git-tree-sha1 = "8e472b20896e3a726553ccfa8754c3f40ea115f2"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "593500ee452324b861b67d79c0a0226231940e81addd6dc779a5c87a649ac1e1"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.powerpc64le-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "riscv64"
git-tree-sha1 = "261148d9a6146b03ba22832939d4640005147daa"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "0666f55567b910a32904b3056c7f37e17894d2fb8bd51a4559d2904f8c84693c"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.riscv64-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "2b2ba367a90c8032f4f52db2234415ed4cbd340a"
os = "macos"

    [[SSGraphBLAS.download]]
    sha256 = "bae901b20a7c21c2a2e9d71c1169b2c7a74b4ddf1be5e1a88d2f3877716306b2"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.x86_64-apple-darwin.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "187516bc4f61defb9a499c518f358cfa07a8ce88"
libc = "glibc"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "cd27f46eebcf07cb498d35533f949875ddc33e7f8ae40096b31906581337f477"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.x86_64-linux-gnu.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "a96143789e5877fa92d9c698816eb1f4872348af"
libc = "musl"
os = "linux"

    [[SSGraphBLAS.download]]
    sha256 = "90c5f7071ac820973374cb2f3673119f0b74d6109e2fb1bbde478c2fdc0862ff"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.x86_64-linux-musl.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "239e808ea6cc0d2b3fe44f3f31823607ede1e8ae"
os = "freebsd"

    [[SSGraphBLAS.download]]
    sha256 = "24c4f8048c85eff9802974424320153c962d4a94197fdf5be024788feb940545"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.x86_64-unknown-freebsd.tar.gz"
[[SSGraphBLAS]]
arch = "x86_64"
git-tree-sha1 = "bf42af2e9d5ef85badd012a5b165b77791842afc"
os = "windows"

    [[SSGraphBLAS.download]]
    sha256 = "16f6aca7d6a13fc29970b1d51007c6ddff491f68fa82f312ce52744860499da5"
    url = "https://github.com/JuliaBinaryWrappers/SSGraphBLAS_jll.jl/releases/download/SSGraphBLAS-v10.2.0+0/SSGraphBLAS.v10.2.0.x86_64-w64-mingw32.tar.gz"
